=== twalrat1/cse445_a4/NationalParks.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="githuburl"
    xmlns:np="githuburl.xsd"
    elementFormDefault="qualified" attributeFormDefault="unqualified">
<element name="NationalParks">
    <complexType>
        <sequence>
            <element name="NationalPark" minOccurs="1" maxOccurs="unbounded">
                <complexType>
                    <sequence>
                        <element name="Name" type="string"/>
                        <element name="Phone" type="string" minOccurs="1" maxOccurs="unbounded"/>
                        <element name="address">
                            <complexType>
                                <sequence>
                                    <element name="Number" type="integer"/>
                                    <element name="Street" type="string"/>
                                    <element name="City" type="string"/>
                                    <element name="State" type="string"/>
                                    <element name="Zip" type="integer"/>
                                </sequence>
                                <attribute name="NearestAirport" type="string" use="required"/>
                            </complexType>
                        </element>
                    </sequence>
                    <attribute name="Rating" type="decimal" use="optional"/>
                </complexType>
            </element>
        </sequence>
    </complexType>
</element>

=== twalrat1/cse445_a4/NationalParks.xml
<?xml version="1.0" encoding="UTF-8"?>
<NationalParks xmlns="https://twalrat1.github.io/cse445_a4/NationalParks.xsd"
        xmlns:np="https://twalrat1.github.io/cse445_a4/NationalParks.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://twalrat1.github.io/cse445_a4/NationalParks.xsd">
    <NationalPark Rating="4.9">
        <Name>Grand Canyon</Name>
        <Phone>928-638-7496</Phone>
        <Phone>888-297-2757</Phone>
        <Phone>866-499-2574</Phone>
        <Address NearestAirport="FlagStaff">
            <Number>8</Number>
            <Street>S Entrance Road</Street>
            <City>Grand Canyon</City>
            <State>AZ</State>
            <Zip>86023</Zip>
        </Address>
    </NationalPark>
    <NationalPark>
        <Name>Great Smoky Mountains</Name>
        <Phone>865-436-1200</Phone>
        <Address NearestAirport="McGee-Tyson">
            <Number>107</Number>
            <Street>Park Headquarters Road</Street>
            <City>Gatlinburg</City>
            <State>TN</State>
            <Zip>37738</Zip>
        </Address>
    </NationalPark>
    <NationalPark Rating="4.8">
        <Name>Zion</Name>
        <Phone>435-772-3256</Phone>
        <Address NearestAirport="St. George Regional">
            <Number>1</Number>
            <Street>Zion Park Blvd</Street>
            <City>Springdale</City>
            <State>UT</State>
            <Zip>84767</Zip>
        </Address>
    </NationalPark>
    <NationalPark>
        <Name>Joshua Tree</Name>
        <Phone>760-367-5500</Phone>
        <Phone>760-368-4367</Phone>
        <Phone>760-367-5554</Phone>
        <Phone>760-367-3001</Phone>
        <Address NearestAirport="Palm Springs International">
            <Number>74485</Number>
            <Street>National Park Drive</Street>
            <City>Twentynine Palms</City>
            <State>CA</State>
            <Zip>92277</Zip>
        </Address>
    </NationalPark>
    <NationalPark Rating="4.6">
        <Name>Indiana Dunes</Name>
        <Phone>219-395-1882</Phone>
        <Address NearestAirport="Gary Regional">
            <Number>1215</Number>
            <Street>IN-49</Street>
            <City>Porter</City>
            <State>IN</State>
            <Zip>46304</Zip>
        </Address>
    </NationalPark>
    <NationalPark>
        <Name>Rocky Mountain</Name>
        <Phone>970-586-1206</Phone>
        <Phone>970-586-1319</Phone>
        <Phone>877-444-6777</Phone>
        <Address NearestAirport="Denver International">
            <Number>1000</Number>
            <Street>US Hwy 36</Street>
            <City>Estes Park</City>
            <State>CO</State>
            <Zip>80517</Zip>
        </Address>
    </NationalPark>
    <NationalPark>
        <Name>Acadia</Name>
        <Phone>207-288-3338</Phone>
        <Address NearestAirport="Hancock County">
            <Number>25</Number>
            <Street>Visitor Center Road</Street>
            <City>Bar Harbor</City>
            <State>ME</State>
            <Zip>04609</Zip>
        </Address>
    </NationalPark>
    <NationalPark Rating="4.9">
        <Name>Grand Teton</Name>
        <Phone>307-739-3399</Phone>
        <Address NearestAirport="Jackson Hole">
            <Number>103</Number>
            <Street>Headquarters Loop</Street>
            <City>Moose</City>
            <State>WY</State>
            <Zip>83012</Zip>
        </Address>
    </NationalPark>
    <NationalPark>
        <Name>Olympic</Name>
        <Phone>360-565-3130</Phone>
        <Phone>360-797-5677</Phone>
        <Address NearestAirport="Victoria International">
            <Number>3002</Number>
            <Street>Mount Angeles Road</Street>
            <City>Port Angeles</City>
            <State>WA</State>
            <Zip>98362</Zip>
        </Address>
    </NationalPark>
    <NationalPark>
        <Name>Glacier</Name>
        <Phone>406-888-7800</Phone>
        <Address NearestAirport="Glacier Park International">
            <Number>64</Number>
            <Street>Grinnel Drive</Street>
            <City>West Glacier</City>
            <State>MT</State>
            <Zip>59936</Zip>
        </Address>
    </NationalPark>
    <NationalPark Rating="4.8">
        <Name>Cuyahoga Valley</Name>
        <Phone>440-717-3890</Phone>
        <Phone>440-546-5945</Phone>
        <Address NearestAirport="Cleveland Hopkins International">
            <Number>6947</Number>
            <Street>Riverview Road</Street>
            <City>Peninsula</City>
            <State>OH</State>
            <Zip>44264</Zip>
        </Address>
    </NationalPark>
</NationalParks>
